name: Dao Test
on:
  push:
    branches:
      - master
      - development
      - android-testing
  pull_request:
    branches:
      - master
      - development
      - android-testing

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}
      # Needed to accept licenses
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3


      - name: Run connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: ./gradlew data:connectedAndroidTest

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-reports
          path: app/build/test-results

  report:
    runs-on: ubuntu-latest
    needs: test # The report job will run after dao-test job
    if: ${{ always() }} # IMPORTANT: Execute report job regardless of status
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: reports

      - name: Dao est Report
        uses: asadmansr/android-test-report-action@v1.2.0



